_wandb:
    value:
        cli_version: 0.21.4
        e:
            tzjopdxbzziti45xlw71lc0zvlg021y9:
                args:
                    - --dataset.repo_id=sakemyali/m2set
                    - --batch_size=32
                    - --steps=100000
                    - --output_dir=outputs/train/svlam2
                    - --job_name=svlam2
                    - --save_freq=5000
                    - --policy.repo_id=sakemyali/svlam2
                    - --policy.device=cuda
                    - --policy.type=smolvla
                    - --policy.push_to_hub=true
                    - --wandb.enable=true
                cpu_count: 160
                cpu_count_logical: 160
                disk:
                    /:
                        total: "2162185003008"
                        used: "819976060928"
                executable: /opt/venv/bin/python
                gpu: AMD Instinct MI300X VF
                gpu_amd:
                    - id: "0"
                      maxPower: "750.0"
                      mclkRange: 900Mhz - 1300Mhz
                      model: "0x74b5"
                      performanceLevel: auto
                      sclkRange: 500Mhz - 2100Mhz
                      series: AMD Instinct MI300X VF
                      sku: M3000100
                      uniqueId: "0x6380e77ea73806bb"
                      vbiosVersion: 113-M3000100-103
                      vendor: Advanced Micro Devices, Inc. [AMD/ATI]
                gpu_count: 1
                host: robotics-jupyter-launcher-8451
                memory:
                    total: "2029207171072"
                os: Linux-6.1.0-39-amd64-x86_64-with-glibc2.39
                program: /opt/venv/bin/lerobot-train
                python: CPython 3.12.3
                root: outputs/train/svlam2
                startedAt: "2025-12-14T06:14:28.413749Z"
                writerId: tzjopdxbzziti45xlw71lc0zvlg021y9
        m: []
        python_version: 3.12.3
        t:
            "1":
                - 1
                - 11
                - 41
                - 49
                - 51
                - 71
                - 83
            "2":
                - 1
                - 11
                - 41
                - 49
                - 51
                - 71
                - 83
            "3":
                - 13
                - 15
                - 16
                - 61
            "4": 3.12.3
            "5": 0.21.4
            "6": 4.53.3
            "10":
                - 21
            "12": 0.21.4
            "13": linux-x86_64
batch_size:
    value: 32
checkpoint_path:
    value: null
dataset:
    value:
        episodes: null
        image_transforms:
            enable: false
            max_num_transforms: 3
            random_order: false
            tfs:
                affine:
                    kwargs:
                        degrees:
                            - -5
                            - 5
                        translate:
                            - 0.05
                            - 0.05
                    type: RandomAffine
                    weight: 1
                brightness:
                    kwargs:
                        brightness:
                            - 0.8
                            - 1.2
                    type: ColorJitter
                    weight: 1
                contrast:
                    kwargs:
                        contrast:
                            - 0.8
                            - 1.2
                    type: ColorJitter
                    weight: 1
                hue:
                    kwargs:
                        hue:
                            - -0.05
                            - 0.05
                    type: ColorJitter
                    weight: 1
                saturation:
                    kwargs:
                        saturation:
                            - 0.5
                            - 1.5
                    type: ColorJitter
                    weight: 1
                sharpness:
                    kwargs:
                        sharpness:
                            - 0.5
                            - 1.5
                    type: SharpnessJitter
                    weight: 1
        repo_id: sakemyali/m2set
        revision: null
        root: null
        streaming: false
        use_imagenet_stats: true
        video_backend: torchcodec
env:
    value: null
eval:
    value:
        batch_size: 50
        n_episodes: 50
        use_async_envs: false
eval_freq:
    value: 20000
job_name:
    value: svlam2
log_freq:
    value: 200
num_workers:
    value: 4
optimizer:
    value:
        betas:
            - 0.9
            - 0.95
        eps: 1e-08
        grad_clip_norm: 10
        lr: 0.0001
        type: adamw
        weight_decay: 1e-10
output_dir:
    value: outputs/train/svlam2
policy:
    value:
        adapt_to_pi_aloha: false
        add_image_special_tokens: false
        attention_mode: cross_attn
        chunk_size: 50
        device: cuda
        empty_cameras: 0
        expert_width_multiplier: 0.75
        freeze_vision_encoder: true
        license: null
        load_vlm_weights: false
        max_action_dim: 32
        max_period: 4
        max_state_dim: 32
        min_period: 0.004
        n_action_steps: 50
        n_obs_steps: 1
        normalization_mapping:
            ACTION: MEAN_STD
            STATE: MEAN_STD
            VISUAL: IDENTITY
        num_expert_layers: -1
        num_steps: 10
        num_vlm_layers: 16
        optimizer_betas:
            - 0.9
            - 0.95
        optimizer_eps: 1e-08
        optimizer_grad_clip_norm: 10
        optimizer_lr: 0.0001
        optimizer_weight_decay: 1e-10
        pad_language_to: longest
        prefix_length: -1
        pretrained_path: null
        private: null
        push_to_hub: true
        repo_id: sakemyali/svlam2
        resize_imgs_with_padding:
            - 512
            - 512
        scheduler_decay_lr: 2.5e-06
        scheduler_decay_steps: 30000
        scheduler_warmup_steps: 1000
        self_attn_every_n_layers: 2
        tags: null
        tokenizer_max_length: 48
        train_expert_only: true
        train_state_proj: true
        type: smolvla
        use_amp: false
        use_cache: true
        use_delta_joint_actions_aloha: false
        vlm_model_name: HuggingFaceTB/SmolVLM2-500M-Video-Instruct
resume:
    value: false
save_checkpoint:
    value: true
save_freq:
    value: 5000
scheduler:
    value:
        decay_lr: 2.5e-06
        num_decay_steps: 30000
        num_warmup_steps: 1000
        peak_lr: 0.0001
        type: cosine_decay_with_warmup
seed:
    value: 1000
steps:
    value: 100000
use_policy_training_preset:
    value: true
wandb:
    value:
        disable_artifact: false
        enable: true
        entity: null
        mode: null
        notes: null
        project: lerobot
        run_id: null
